// <auto-generated />
using CoreMvc5_Routing.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreMvc5_Routing.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20220418071030_newMigration")]
    partial class newMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreMvc5_Routing.Models.Cars", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("汽車廠牌製造商");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("汽車分類");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("汽車名稱");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("汽車售價");

                    b.Property<int>("SoldNumber")
                        .HasColumnType("int")
                        .HasComment("汽車年度銷售數字");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasComment("汽車年份");

                    b.HasKey("Id");

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
